### ISSUE TITLE
No support for algebraic notation

### ISSUE THREAD

**Issue by lucrae** [Cqsi/lichs#1]
Lichs currently only supports move input using [UCI](https://en.m.wikipedia.org/wiki/Universal_Chess_Interface)  (e.g. e2e4) and not [algrebraic notation](https://en.m.wikipedia.org/wiki/Algebraic_notation_(chess))  (e.g. e4). While UCI is standard for engine chess and computer communication of moves, algebraic notation is very much the standard for modern human play.

Support for algebraic notation would be great for usability as players would not need to learn a new coordinate system to make their moves.

**Comment by Cqsi** [comment]
I'm unsure on how to do this, but if I find a way I'm definitely going to change it.

**Comment by ralacerda** [comment]
I was reading the python-chess documentation and found a way to convert UCI to algebraic and vice-versa.

python-chess also accepts `push_san("e4")`, so we only need to do `parse_san("e4")` to get the UCI code and send it to Lichess.

When reciving an UCI move, we can use `Move.from_uci("b1c3")`  to get a "move", and then `san(move)` to get the algebraic notation of the move.

Small example 

```python
import chess

board = chess.Board()
board.push_san("e4")
print(board)

board.san(chess.Move.from_uci("e7e5"))
```

**Comment by Cqsi** [comment]
@ralacerda Oh my! Thank you! I didn't write more on what the problem was here, but you figured it out (the problem was that the Lichess API only accept UCI-format). I didn't know python-chess had the ability to parse algebraic to UCI. I'm definitely going to try to implement this. Thank you once again!

**Comment by ralacerda** [comment]
I think I'll make a new function `make_move(move)`, this way if we need to change the way the class Game works, we don't need to re-implement sending the movies to the local board and lichess.  
I'll work on this and send a PR so we can test it out.

**Comment by Cqsi** [comment]
@ralacerda Yes, good idea.

**Comment by Cqsi** [comment]
@ralacerda No worries, but some time has gone now, are you working on it or shall I implement this?

**Comment by Cqsi** [comment]
I have now implemented algebraic notation, check it out if you have time. @ralacerda I haven't added a `make_move(move)` function, but I'll think I'll still close this issue.
