### ISSUE TITLE
Issues with API access token error message

### ISSUE THREAD

**Issue by lucrae** [Cqsi/lichs#2]
If a user attempts to launch lichs without an API key, the following error is displayed:

```
The API-key is either empty or wrong. Please run the command 'lichess' and input your API-key as a second argument, i.e 'lichess <api_key>'. If you need more help, please see the instructions in the Github README: 
https://github.com/Cqsi/lichess_terminal#how-to-generate-a-personal-api-token
```

But:

- The command is `lichs` not `lichess`.
- The header-tied link is `https://github.com/Cqsi/lichs#how-to-generate-a-personal-api-key` not `https://github.com/Cqsi/lichess_terminal#how-to-generate-a-personal-api-token`.
- Lichess refers to the API keys as "API access tokens" not "API-keys." This isn't crucial to change, but could help consistency for users.

**Comment by Cqsi** [comment]
Thank you, this was an easy fix!
