### ISSUE TITLE
README.md contains Windows-centric instructions.

### ISSUE THREAD

**Issue by lucrae** [Cqsi/lichs#3]
By default, READMEs should be OS-neutral or following GNU/Linux conventions as they are the most easily mapped to other OSs. This is of course unless the program is a Windows-exclusive, but that doesn't make a lot of sense for this.

The README.md contains a few very Windows-centric instructions that may confuse non-Windows users, e.g:

- The instructions say to use `C:\> pip install lichs` instead of simply `pip install lichs` or (`$ pip install lichs` to indicate that it's in a shell).
- Step 6 of "How to generate a personal API-key" says to "Jump into CMD" which is a specific program. Instead of "CMD" it should say "terminal", which is the generic term for the progams one can use to input the commands.
- Under Usage it explicity says to type the command into the "Windows Command Prompt."

**Comment by Cqsi** [comment]
Thanks, I planned to only have the prorgram on Windows, but then I discovered how easy it was to make the program platform-independent using PyPi, so I forgot to change it in the README

**Comment by lucrae** [comment]
Awesome, I presumed it'd just be something like that.
