### ISSUE TITLE
I cant put the token...

### ISSUE THREAD

**Issue by 9acca9** [Cqsi/lichs#39]
Sorry my dumb question but... i cant paste the token.... is strange because i have a previous version of lichs, and there i can paste... but cant in this "new version". Cant even write.
Probably a easy solution, but... i dont know how.
Thanks.

**Comment by pabrams** [comment]
I have the same issue.  How did you fix it?

**Comment by 9acca9** [comment]
> I have the same issue. How did you fix it?

When i ask, i have in mind the first versions of lichs. Now is like this:

"Jump into your terminal and write lichs <api_token> (put your API token instead of <api_token>) and run the command. To get this clear, an example would have been lichs lzRceo5XOUND74Lm. You should then see a message to confirm that the API token has been saved."
