### ISSUE TITLE
readme.md has a word error - very minor

### ISSUE THREAD

**Issue by actor10** [Cqsi/lichs#42]
Near the bottom of the readme, it says:

(N is for Knight, since Rook uses K)

It's "King" that uses K.

**Comment by Cqsi** [comment]
Sorry for replying so late. I can of course change it myself, but if you want to test you could make the edit yourself and become a contributor to this project. What you need to do is:

1. Fork this project
2. Make the change
3. Make a pull request (that I then accept)

**Comment by actor10** [comment]
I'll do it!  (I've never done one before so might as well start with a text fix.)

**Comment by Cqsi** [comment]
Alright, I thought so! Go ahead and see if you can do it. I can help if you need help.

**Comment by actor10** [comment]
I think I did the pull request okay.

BTW, I'm working on an app for Android and IOS where you can play on Lichess by voice.  Also, play against the Komodo and Stockfish engines.

**Comment by Cqsi** [comment]
Thank you, I merged the pull request now. You should see your profile under "Contributors" now! Congrats on your first contribution to an open-source project!

The app sounds really cool. If you use Lichs and you bump into some problems be sure to contact me!

**Comment by Cqsi** [comment]
Can I close this issue now? @actor10

**Comment by actor10** [comment]
Yes.
