### ISSUE TITLE
Loop menu

### ISSUE THREAD

**Issue by ralacerda** [Cqsi/lichs#5]
Hello,

I was thinking about adding a Loop menu (one of the TODOs in the code).
This way it doesn't exit abruptly if you write a wrong command.

Something similar to:

```python
def menu(account_data, client, board, session):
    player_username = account_data["username"]
    print("Welcome to Lichess {}!".format(player_username))

    while True:
        print("""
        P to play
        H for help
        Q to quit
        """)
        ans = input("command: ").lower()

        if ans.lower== "q":
            sys.exit()

```

This use the player would also go back to the menu after a game, maybe change a configuration, token, etc.

I can try to remake the current menu in this format so we can test it out before adding new features.

**Comment by Cqsi** [comment]
@ralacerda Yeah, this is a good idea. I have also thought about adding configurations, e.g. If you want to have UCI-format or algebraic notation. You can try to implement this yourself, but remember to ask if there's something you don't understand in the code (or similar). Thank you once again for a nice suggestion!

**Comment by samthegitguy** [comment]
https://github.com/samthegitguy/lichs/commit/25e53156ad569a848f97198025418668ede6b57a works a little on this, at least for the game time selector. I might work on this more later.
